version: '3.8'

services:
  web:
    build: .
    image: aass-frontend-service:latest
    command: "npm run serve"
    volumes:
      - .:/aass-frontend-service/
    ports:
      - 8080:8080
    env_file:
      - .env
